//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sys_connettore_database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GFTA_COMUNE
    {
        public string Codice { get; set; }
        public string Descr { get; set; }
        public Nullable<System.DateTime> DataOraSync { get; set; }
    }
}
