//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sys_connettore_database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOCG_PRIMANOTA
    {
        public decimal Ditta { get; set; }
        public string GoKey { get; set; }
        public decimal Stato { get; set; }
        public decimal Esito { get; set; }
        public string Operazione { get; set; }
        public string ModReg { get; set; }
        public Nullable<decimal> TipoRec { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public Nullable<System.DateTime> DataDocOri { get; set; }
        public string NumDocOri { get; set; }
        public string CodiceCausale { get; set; }
        public string DescrizioneAggCode { get; set; }
        public string CodiceValuta { get; set; }
        public string CodiceConto { get; set; }
        public Nullable<decimal> TipoCF { get; set; }
        public Nullable<int> CodiceCliFor { get; set; }
        public Nullable<decimal> IndDareAvere { get; set; }
        public Nullable<decimal> ImpOperEuro { get; set; }
        public string NumReg { get; set; }
        public Nullable<decimal> IndStato { get; set; }
    }
}
