//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sys_connettore_database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOCM_DOCUMENTO
    {
        public long ID { get; set; }
        public Nullable<long> Id_Operazione { get; set; }
        public Nullable<int> Id_Operazione_Prog { get; set; }
        public Nullable<long> Id_Operazione_Rif { get; set; }
        public Nullable<System.Guid> Id_Elaborazione_1 { get; set; }
        public Nullable<System.Guid> Id_Elaborazione_2 { get; set; }
        public Nullable<decimal> Stato { get; set; }
        public Nullable<decimal> Esito { get; set; }
        public Nullable<int> Import { get; set; }
        public Nullable<int> Del { get; set; }
        public Nullable<decimal> Err { get; set; }
        public string Err_Note { get; set; }
        public Nullable<decimal> Operazione { get; set; }
        public Nullable<decimal> Operazione_Mod { get; set; }
        public Nullable<System.DateTime> Data_Insert { get; set; }
        public Nullable<System.DateTime> Data_Update { get; set; }
        public Nullable<decimal> Ditta { get; set; }
        public string Key_1 { get; set; }
        public string Key_2 { get; set; }
        public string Key_Rif_1 { get; set; }
        public string Key_Rif_2 { get; set; }
        public Nullable<decimal> TipoRec { get; set; }
        public Nullable<int> Riga { get; set; }
        public string CodDocumento { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public Nullable<System.DateTime> DataDoc { get; set; }
        public string CodSez { get; set; }
        public Nullable<int> NumDoc { get; set; }
        public string NumDocOri { get; set; }
        public Nullable<decimal> TipoCF { get; set; }
        public Nullable<int> CodCliFor { get; set; }
        public string CodPag { get; set; }
        public string CodDeposito { get; set; }
        public string Aliva { get; set; }
        public string CodCauPrestazione { get; set; }
        public Nullable<System.DateTime> DataDaCompetenzaTes { get; set; }
        public Nullable<System.DateTime> DataACompetenzaTes { get; set; }
        public string DescrizioneAggCoGe { get; set; }
        public string CodSdi { get; set; }
        public Nullable<decimal> IndicatoreTipoRiga { get; set; }
        public string CodArticolo { get; set; }
        public string DescrizioneArticolo { get; set; }
        public string Um { get; set; }
        public Nullable<decimal> Qta { get; set; }
        public Nullable<decimal> Prezzo { get; set; }
        public Nullable<decimal> Sc1 { get; set; }
        public Nullable<decimal> Sc2 { get; set; }
        public string AlivaRiga { get; set; }
        public string ContoContropartita { get; set; }
        public Nullable<decimal> FlgRitAcconto { get; set; }
        public Nullable<decimal> FlgConIntegrativo { get; set; }
        public Nullable<System.DateTime> DataDaCompetenzaRiga { get; set; }
        public Nullable<System.DateTime> DataACompetenzaRiga { get; set; }
        public Nullable<System.DateTime> DataCompetenzaIva { get; set; }
        public Nullable<decimal> IndStato { get; set; }
    }
}
