//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sys_connettore_database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GORP_RITENUTEP
    {
        public long ID { get; set; }
        public Nullable<long> Id_Operazione { get; set; }
        public Nullable<int> Id_Operazione_Prog { get; set; }
        public Nullable<long> Id_Operazione_Rif { get; set; }
        public Nullable<System.Guid> Id_Elaborazione_1 { get; set; }
        public Nullable<System.Guid> Id_Elaborazione_2 { get; set; }
        public Nullable<decimal> Stato { get; set; }
        public Nullable<decimal> Esito { get; set; }
        public Nullable<int> Import { get; set; }
        public Nullable<int> Del { get; set; }
        public Nullable<decimal> Err { get; set; }
        public string Err_Note { get; set; }
        public Nullable<decimal> Operazione { get; set; }
        public Nullable<decimal> Operazione_Mod { get; set; }
        public Nullable<System.DateTime> Data_Insert { get; set; }
        public Nullable<System.DateTime> Data_Update { get; set; }
        public string Key_1 { get; set; }
        public string Key_2 { get; set; }
        public string Key_Rif_1 { get; set; }
        public string Key_Rif_2 { get; set; }
        public Nullable<int> ProgFlusso { get; set; }
        public Nullable<decimal> TipoRec { get; set; }
        public Nullable<decimal> Ditta { get; set; }
        public Nullable<System.DateTime> DataReg { get; set; }
        public string NumDocOri { get; set; }
        public Nullable<System.DateTime> DataDocOri { get; set; }
        public string CodSez { get; set; }
        public Nullable<int> NumDoc { get; set; }
        public Nullable<decimal> TipoPrest { get; set; }
        public string CodiceCauPrest { get; set; }
        public Nullable<int> CodFor { get; set; }
        public Nullable<decimal> CodTribRa { get; set; }
        public Nullable<decimal> CodTribRp { get; set; }
        public Nullable<decimal> TotDoc { get; set; }
        public Nullable<decimal> TotIva { get; set; }
        public Nullable<decimal> IndSegno { get; set; }
        public Nullable<decimal> IndAssRa { get; set; }
        public Nullable<decimal> ImportoCi { get; set; }
        public Nullable<decimal> ImportoPrNs { get; set; }
        public Nullable<decimal> ImponibileSoRa { get; set; }
        public Nullable<decimal> PercRa { get; set; }
        public Nullable<decimal> ImportoRa { get; set; }
        public Nullable<decimal> ImportoAlRi { get; set; }
        public Nullable<decimal> ImportoEnCa { get; set; }
        public Nullable<decimal> ImportoNsRa { get; set; }
        public Nullable<decimal> ImportoFrRp { get; set; }
        public Nullable<decimal> ImponibileSoRp { get; set; }
        public Nullable<decimal> PercRp { get; set; }
        public Nullable<decimal> PercRpCa { get; set; }
        public Nullable<decimal> ImportoRpPe { get; set; }
        public Nullable<decimal> ImportoRpCa { get; set; }
        public Nullable<decimal> AnnoComp770 { get; set; }
        public Nullable<decimal> CertRaSt { get; set; }
        public Nullable<System.DateTime> DataInAtt { get; set; }
        public Nullable<System.DateTime> DataFiAtt { get; set; }
        public Nullable<decimal> PagTot { get; set; }
        public Nullable<System.DateTime> DataPag { get; set; }
        public Nullable<decimal> MeseCompPag { get; set; }
        public Nullable<decimal> AnnoCompPag { get; set; }
        public Nullable<decimal> ImportoPag { get; set; }
        public Nullable<decimal> ImportoAbb { get; set; }
        public Nullable<decimal> ImportoCiPag { get; set; }
        public Nullable<decimal> ImportoPrNsPag { get; set; }
        public Nullable<decimal> ImponibileSoRaPag { get; set; }
        public Nullable<decimal> ImportoRaPag { get; set; }
        public Nullable<decimal> ImportoAlRiPag { get; set; }
        public Nullable<decimal> ImportoEnCaPag { get; set; }
        public Nullable<decimal> ImportoNsRaPag { get; set; }
        public Nullable<decimal> ImportoFrRpPag { get; set; }
        public Nullable<decimal> ImponibileSoRpPag { get; set; }
        public Nullable<decimal> ImportoRpPePag { get; set; }
        public Nullable<decimal> ImportoRpCaPag { get; set; }
        public Nullable<decimal> ImportoCredImposta { get; set; }
        public Nullable<decimal> MeseCompVersRa { get; set; }
        public Nullable<decimal> AnnoCompVersRa { get; set; }
        public Nullable<decimal> TipoVers { get; set; }
        public Nullable<decimal> CodAbiVersRa { get; set; }
        public Nullable<decimal> CodCabVersRa { get; set; }
        public string SerieVersRa { get; set; }
        public string QuietVersRa { get; set; }
        public string CcPostaleVersRa { get; set; }
        public Nullable<decimal> MeseCompVersRp { get; set; }
        public Nullable<decimal> AnnoCompVersRp { get; set; }
        public string TipoVersRp { get; set; }
        public Nullable<decimal> CodAbiVersRp { get; set; }
        public Nullable<decimal> CodCabVersRp { get; set; }
        public string SerieVersRp { get; set; }
        public string QuietVersRp { get; set; }
        public string CcPostaleVersRp { get; set; }
        public Nullable<decimal> CertRaStPag { get; set; }
        public Nullable<decimal> CertRpStPag { get; set; }
    }
}
